version: '3'

services:
  mariadb:
    image: 'wodby/mariadb:10.1-3.3.8'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql

  php:
    image: 'wodby/drupal-php:7.1-dev-${OS}4.8.5'
    environment:
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_AUTOSTART: 1
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 1
      #PHP_XDEBUG_REMOTE_HOST: $PHP_XDEBUG_REMOTE_HOST
    volumes:
      - ./:/var/www/html
      - ./drush:/etc/drush

  apache:
    image: 'wodby/apache:2.4-4.0.2'
    depends_on:
      - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_VHOST_PRESET: php
      APACHE_DOCUMENT_ROOT: /var/www/html/web
      APACHE_BACKEND_HOST: php
    volumes:
      - ./:/var/www/html
    labels:
      traefik.backend: 'dgo_apache_1'
      traefik.port: '80'
      traefik.frontend.rule: 'Host:dgo.docker.localhost'

  traefik:
    image: traefik
    container_name: "dgo_traefik"
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db:
