version: '3'

services:

  mariadb:
    image: 'wodby/mariadb:10.1-3.3.9'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db:/var/lib/mysql

  php:
    image: 'wodby/drupal-php:7.1-dev-4.9.0'
    restart: always
    environment:
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
    volumes:
      - .:/var/www/html
      - ./drush:/etc/drush
    networks:
      - default
      - proxy

  apache:
    image: 'wodby/apache:2.4-4.0.2'
    restart: always
    depends_on:
      - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_VHOST_PRESET: php
      APACHE_DOCUMENT_ROOT: /var/www/html/web
      APACHE_BACKEND_HOST: php
    volumes:
      - .:/var/www/html
    labels:
      traefik.enable: 'true'
      traefik.docker.network: 'proxy'
      traefik.frontend.protocol: 'https'
      traefik.frontend.port: '443'
      traefik.frontend.rule: 'Host:vet.dev.178.128.83.195.xip.io,can.dev.178.128.83.195.xip.io'
    networks:
      - default
      - proxy

  memcached:
    restart: always
    image: 'wodby/memcached:1-2.2.0'

volumes:
  db:

networks:
  proxy:
    external: true
